baseURL = 'https://certer.mnescho.space/'
locale = 'en-us'
title = 'Certer Documentation'

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = false
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # Theme Options
  themeColor = "emerald" # Options: blue, green, red, emerald, etc.
  custom_css = ["css/custom.css"]
  
  # Header/Brand
  logo = "img/logo.svg"

  [params.docs]
    darkMode = true
  
  # Footer Options
  [params.footer]
    copyright = "© 2026 Mensch0mat"
