baseURL = 'https://certer.mnescho.space/'
locale = 'en-us'
title = 'Certer Documentation'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.footer]
    copyright = "© 2026 Mensch0mat"
